# Generated by Django 3.2.6 on 2021-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20210827_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
